language: go

go:
  - 1.15.3

before_install:
  - go get -t -v ./...
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

script:
  - echo "Start license scan"
  - fossa init
  - fossa analyze
  - echo "Running golangci-lint" && golangci-lint run ./...
  - echo "Building" && CGO_ENABLED=0 go build -ldflags="-X 'main.Version=v1.0.0'" -o ./app cmd/server/main.go
  - echo "Running tests" && go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - cd <SOURCE_DIR> && fossa test
  - bash <(curl -s https://codecov.io/bash)